using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AstRevitTool.Core.Export
{
    internal class ColladaTemplates
    {
        public static string NodeMaterialEffect = "  <effect id=\"effect-Node\" name=\"Node Material\">\r\n\t\t<profile_COMMON>\r\n\t\t\t<technique sid=\"standard\">\r\n                <phong>\r\n                    <ambient>\r\n                        <color> 0.5 0.5 0.5 1.0</color>\r\n\t\t\t\t\t</ambient>\r\n\t\t\t\t\t<diffuse>\r\n\t\t\t\t\t\t<color>1.0 1.0 1.0 1.0</color>\r\n\t\t\t\t\t</diffuse>\r\n\t\t\t\t\t<transparent opaque=\"A_ONE\">\r\n                        <color> 1.0 1.0 1.0 1.0</color>\r\n\t\t\t\t\t</transparent>\r\n\t\t\t\t\t<transparency>\r\n\t\t\t\t\t\t<float>1</float>\r\n\t\t\t\t\t</transparency>\r\n\t\t\t\t</phong>\r\n\t\t\t</technique>\r\n\t\t</profile_COMMON>\r\n\t\t<extra>\r\n\t\t\t<technique profile=\"LUMION\">\r\n                <surface_type>invisible</surface_type>\r\n            </technique>\r\n        </extra>\r\n    </effect>\r\n";
        public static string NodeMaterial = "  <material id=\"material-Node\" name=\"Node Material\">\r\n\t\t<instance_effect url=\"#effect-Node\" />\r\n    </material>\r\n";
        public static string NodeGeometry = "   <geometry id=\"Node\" name=\"Node Geometry\">\r\n\t\t<mesh>\r\n\t\t\t<source id=\"Node-positions\">\r\n                <float_array id=\"Node-positions-array\" count=\"9\">0 0 -0.000001 0.000001 0 0.000001 -0.000001 0 0.01</float_array>\r\n\t\t\t\t<technique_common>\r\n\t\t\t\t\t<accessor source=\"#Node-positions-array\" count=\"3\" stride=\"3\">\r\n\t\t\t\t\t\t<param name=\"X\" type=\"float\"/>\r\n\t\t\t\t\t\t<param name=\"Y\" type=\"float\"/>\r\n\t\t\t\t\t\t<param name=\"Z\" type=\"float\"/>\r\n\t\t\t\t\t</accessor>\r\n\t\t\t\t</technique_common>\r\n\t\t\t</source>\r\n\t\t\t<source id=\"Node-normals\">\r\n                <float_array id=\"Node-normals-array\" count=\"9\">0 1 0 0 1 0 0 1 0</float_array>\r\n\t\t\t\t<technique_common>\r\n\t\t\t\t\t<accessor source=\"#Node-normals-array\" count=\"3\" stride=\"3\">\r\n\t\t\t\t\t\t<param name=\"X\" type=\"float\"/>\r\n\t\t\t\t\t\t<param name=\"Y\" type=\"float\"/>\r\n\t\t\t\t\t\t<param name=\"Z\" type=\"float\"/>\r\n\t\t\t\t\t</accessor>\r\n\t\t\t\t</technique_common>\r\n\t\t\t</source>\r\n\t\t\t<source id=\"Node-uv\">\r\n                <float_array id=\"Node-uv-array\" count=\"6\">0 0 1 0 0 0</float_array>\r\n\t\t\t\t<technique_common>\r\n\t\t\t\t\t<accessor source=\"#Node-uv-array\" count=\"3\" stride=\"2\">\r\n\t\t\t\t\t\t<param name=\"S\" type=\"float\"/>\r\n\t\t\t\t\t\t<param name=\"T\" type=\"float\"/>\r\n\t\t\t\t\t</accessor>\r\n\t\t\t\t</technique_common>\r\n\t\t\t</source>\r\n\t\t\t<vertices id=\"Node-vertices\">\r\n                <input semantic=\"POSITION\" source=\"#Node-positions\"/>\r\n\t\t\t</vertices>\r\n\t\t\t<triangles count=\"1\" material=\"material-Node\">\r\n\t\t\t\t<input offset=\"0\" semantic=\"VERTEX\" source=\"#Node-vertices\"/>\r\n\t\t\t\t<input offset=\"0\" semantic=\"NORMAL\" source=\"#Node-normals\"/>\r\n\t\t\t\t<input offset=\"0\" semantic=\"TEXCOORD\" source=\"#Node-uv\" set=\"0\"/>\r\n\t\t\t\t<p>0 1 2</p>\r\n\t\t\t</triangles>\r\n\t\t</mesh>\r\n\t</geometry>\r\n";
        public static string NodeGeometryInstance = "  <instance_geometry url=\"#Node\">\r\n\t\t<bind_material>\r\n            <technique_common>\r\n                <instance_material target=\"#material-Node\" symbol=\"material-Node\" />\r\n\t\t\t</technique_common>\r\n\t\t</bind_material>\r\n\t</instance_geometry>\r\n";
        public static string ExtraFlattenHierarchy = "  <extra>\r\n        <technique profile=\"LUMION\">\r\n            <flatten_hierarchy>true</flatten_hierarchy>\r\n        </technique>\r\n    </extra>\r\n";
    }
}
